services:
  freqtrade:
    command: >
      trade
      --config /freqtrade/user_data/config.example.json
      --config /freqtrade/user_data/runtime/config.trading-rules.json
      --config /freqtrade/user_data/config.private.json
      --strategy CoinMasterStrategy
