import { useEffect, useState } from 'react';
import { Badge } from '../components/Badge';
import { Button } from '../components/Button';
import { Card } from '../components/Card';
import { DataTable } from '../components/DataTable';
import { Stat } from '../components/Stat';
import { cancelRun, createRun, getConfigurations, getDefaultConfiguration, getHlStagegProjection, getHlStagegStrategy, getResearchCatalog, getRuns, saveConfiguration, setApiToken, type HlStagegProjection, type HlStagegStrategy, type ResearchCatalogEntry, type Run, type StrategyConfig, type StrategyConfiguration } from '../lib/nautilusApi';

type NumberKey = 'ema_period' | 'beta_days' | 'relative_days' | 'z_history_days' | 'wave_history_days' | 'wave_min_count' | 'btc_notional_multiplier' | 'max_gross_to_active' | 'sol_exit_half_z' | 'sol_exit_all_z' | 'sol_max_holding_days' | 'btc_close_trail_fraction';
type ArrayKey = 'wave_quantiles' | 'btc_tp_fractions_initial_qty' | 'sol_size_multipliers_H' | 'sol_entry_z';

function tone(status: string): 'success' | 'danger' | 'neutral' { return status === 'COMPLETED' ? 'success' : status === 'BLOCKED' || status === 'CANCELED' ? 'danger' : 'neutral'; }
function title(key: string) { return key.replaceAll('_', ' '); }

function CsvNumberField({ label, value, onCommit }: { label: string; value: number[]; onCommit: (next: number[]) => void }) {
  const serialized = value.join(',');
  const [draft, setDraft] = useState(serialized);
  useEffect(() => setDraft(serialized), [serialized]);
  function commit() { const next = draft.split(',').map((part) => Number(part.trim())); if (next.length === 3 && next.every(Number.isFinite)) onCommit(next); }
  return <label className="rules-field"><span>{label} (CSV)</span><input value={draft} onChange={(event) => setDraft(event.target.value)} onBlur={commit} /></label>;
}

export function StrategyPage() {
  const [strategy, setStrategy] = useState<HlStagegStrategy | null>(null); const [config, setConfig] = useState<StrategyConfig | null>(null); const [drafts, setDrafts] = useState<StrategyConfiguration[]>([]); const [saved, setSaved] = useState<StrategyConfiguration | null>(null); const [message, setMessage] = useState(''); const [token, setToken] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  async function load() { setLoading(true); setMessage(''); const [sealed, stored, template] = await Promise.allSettled([getHlStagegStrategy(), getConfigurations(), getDefaultConfiguration()]); if (sealed.status === 'fulfilled') setStrategy(sealed.value); if (stored.status === 'fulfilled') { setDrafts(stored.value); const selected = stored.value.find((item) => item.id === window.localStorage.getItem('coinmaster-selected-config')) ?? stored.value[0]; if (selected) { setSaved(selected); setConfig(selected.config); } } if (template.status === 'fulfilled') setConfig((current) => current ?? template.value.config); const failure = [sealed, stored, template].find((result) => result.status === 'rejected'); if (failure?.status === 'rejected') setMessage(failure.reason instanceof Error ? failure.reason.message : 'Unable to load the Strategy page.'); setLoading(false); }
  useEffect(() => { void load(); }, []);
  function updateNumber(key: NumberKey, value: string) { if (value !== '') setConfig((item) => item ? { ...item, [key]: Number(value) } : item); }
  function updateArray(key: ArrayKey, value: number[]) { setConfig((item) => item ? { ...item, [key]: value } : item); }
  async function save() { if (!config || saving) return; if (!Number.isFinite(Number(config.initial_total_usdt)) || Number(config.initial_total_usdt) <= 0) { setMessage('Research draft validation failed: initial total must be a positive number.'); return; } setSaving(true); setMessage('Saving research draft…'); try { const next = await saveConfiguration(config); const refreshed = await getConfigurations(); const persisted = refreshed.find((item) => item.id === next.id); if (!persisted) throw new Error('Saved draft could not be read back.'); setDrafts(refreshed); setSaved(persisted); setConfig(persisted.config); window.localStorage.setItem('coinmaster-selected-config', persisted.id); setMessage(`Research draft saved and read back: ${persisted.config_hash.slice(0, 12)}.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Research draft save failed.'); } finally { setSaving(false); } }
  return <main className="terminal-layout">
    <Card title="Local API access" actions={<Badge tone="neutral">LOCAL</Badge>}><label className="rules-field"><span>Operator token</span><input value={token} type="password" onChange={(event) => setToken(event.target.value)} /><Button onClick={() => { setApiToken(token); window.location.reload(); }}>Connect</Button></label></Card>
    <Card title="Running sealed Stage-G" actions={<Badge tone={strategy?.source_state === 'SEALED_SOURCE_CHECKED' ? 'success' : 'danger'}>{strategy?.source_state ?? (loading ? 'LOADING' : 'UNAVAILABLE')}</Badge>}>
      <p className="muted">Isolated instance <code>hl-stageg-testnet</code> · {strategy?.strategy_id ?? 'UNKNOWN'} · native Sandbox using public MAINNET data. This identity is read-only and separate from every research draft below.</p>
      <p className="muted">Candidate {strategy?.hashes.candidate_sha256 ?? 'UNKNOWN'} · strategy {strategy?.hashes.strategy_sha256 ?? 'UNKNOWN'} · policy {strategy?.hashes.execution_policy_sha256 ?? 'UNKNOWN'}</p>
      <DataTable rows={Object.entries(strategy?.candidate ?? {}).map(([parameter, value]) => ({ id: parameter, parameter, value }))} emptyText="No sealed candidate is available." mobileTitle={(row) => row.parameter} columns={[{ key: 'parameter', header: 'Sealed parameter', render: (row) => row.parameter }, { key: 'value', header: 'Value', render: (row) => row.value }]} />
    </Card>
    <Card title="Sandbox assumptions and unknown account facts" actions={<Badge tone="neutral">HONEST LIMITS</Badge>}><p className="muted">{strategy?.capital_assumption ?? 'UNKNOWN'} · {strategy?.research_comparison_assumption ?? 'UNKNOWN'}.</p><p className="muted">{strategy?.public_venue_profile ?? 'UNKNOWN'} Account margin: {strategy?.account_margin ?? 'UNKNOWN'} · account fee schedule: {strategy?.account_fee_schedule ?? 'UNKNOWN'} · funding: {strategy?.funding_treatment ?? 'UNKNOWN'}.</p></Card>
    <Card title="Promotion" actions={<Badge tone="danger">BLOCKED</Badge>}><p className="muted">Promotion is intentionally unavailable: {strategy?.promotion_reason ?? 'SEPARATE_NATIVE_LIFECYCLE_GATE_REQUIRED'}. Saving a draft never mutates the running Nautilus instance.</p><Button variant="primary" disabled>Promote to running instance</Button></Card>
    <Card title="Research drafts" actions={<Badge tone="neutral">SEPARATE FROM RUNNER</Badge>}>
      <p className="muted">These are immutable local research records for later evaluation. They are not the sealed Stage-G candidate and do not alter <code>hl-stageg-testnet</code>.</p>
      <label className="rules-field"><span>Read-back saved draft</span><select value={saved?.id ?? ''} onChange={(event) => { const next = drafts.find((item) => item.id === event.target.value) ?? null; setSaved(next); setConfig(next?.config ?? config); if (next) window.localStorage.setItem('coinmaster-selected-config', next.id); }}>{drafts.map((item) => <option key={item.id} value={item.id}>{item.config_hash.slice(0, 12)} · {item.created_at}</option>)}</select></label>
      <div className="rules-form-grid">
        <label className="rules-field"><span>Initial TOTAL (template constraint)</span><input disabled value={config?.initial_total_usdt ?? ''} /></label>
        <label className="rules-field"><span>Initial active fraction (template constraint)</span><input disabled type="number" value={String(config?.initial_active_fraction ?? '')} /></label>
        <label className="rules-field"><span>Research venue label only</span><select value={config?.venue ?? ''} onChange={(event) => setConfig((item) => item ? { ...item, venue: (event.target.value || null) as StrategyConfig['venue'] } : item)}><option value="">Unselected</option><option value="bybit">Bybit</option><option value="hyperliquid">Hyperliquid</option></select></label>
        {(['ema_period', 'beta_days', 'relative_days', 'z_history_days', 'wave_history_days', 'wave_min_count', 'btc_notional_multiplier', 'max_gross_to_active', 'sol_exit_half_z', 'sol_exit_all_z', 'sol_max_holding_days', 'btc_close_trail_fraction'] as const).map((key) => <label className="rules-field" key={key}><span>{title(key)}</span><input type="number" value={String(config?.[key] ?? '')} onChange={(event) => updateNumber(key, event.target.value)} /></label>)}
        <label className="rules-field"><span>Max parent notional</span><input value={config?.max_parent_notional ?? ''} onChange={(event) => setConfig((item) => item ? { ...item, max_parent_notional: event.target.value } : item)} /></label>
        <label className="rules-field"><span>Include zero waves (v0 fixed)</span><input disabled type="checkbox" checked={Boolean(config?.include_zero_waves)} /></label>
        <label className="rules-field"><span>Freeze sigma on first SOL fill (v0 fixed)</span><input disabled type="checkbox" checked={Boolean(config?.freeze_sigma_on_first_sol_fill)} /></label>
        <label className="rules-field"><span>Insufficient margin (v0 fixed)</span><select disabled value={config?.insufficient_margin ?? 'reject'}><option value="reject">reject</option></select></label>
        {config ? <><CsvNumberField label="Wave quantiles" value={config.wave_quantiles} onCommit={(next) => updateArray('wave_quantiles', next)} /><CsvNumberField label="BTC TP fractions / initial qty" value={config.btc_tp_fractions_initial_qty} onCommit={(next) => updateArray('btc_tp_fractions_initial_qty', next)} /><CsvNumberField label="SOL multipliers H" value={config.sol_size_multipliers_H} onCommit={(next) => updateArray('sol_size_multipliers_H', next)} /><CsvNumberField label="SOL entry z" value={config.sol_entry_z} onCommit={(next) => updateArray('sol_entry_z', next)} /></> : null}
      </div>
      <p className="muted">Template constraints remain fixed until a separately scoped native implementation. Server validation is authoritative for research-draft saves.</p>
      <div className="rules-btn-group rules-btn-group--mb"><Button variant="primary" disabled={!config || saving} onClick={() => void save()}>{saving ? 'Saving…' : 'Save research draft'}</Button>{saved ? <Badge tone="success">{saved.config_hash.slice(0, 12)}</Badge> : null}</div>{message ? <p className="muted">{message}</p> : null}
    </Card>
  </main>;
}

export function ResearchPage() {
  const [config, setConfig] = useState<StrategyConfiguration | null>(null); const [configs, setConfigs] = useState<StrategyConfiguration[]>([]); const [runs, setRuns] = useState<Run[]>([]); const [catalog, setCatalog] = useState<ResearchCatalogEntry[]>([]); const [message, setMessage] = useState(''); async function load() { try { setRuns(await getRuns()); setCatalog(await getResearchCatalog()); const items = await getConfigurations(); setConfigs(items); const selected = window.localStorage.getItem('coinmaster-selected-config'); setConfig(items.find((item) => item.id === selected) ?? items[0] ?? null); } catch (error) { setMessage(String(error)); } } useEffect(() => { void load(); }, []); async function ensureConfig() { if (config) return config; const selected = window.localStorage.getItem('coinmaster-selected-config'); const existing = (await getConfigurations()).find((item) => item.id === selected); if (existing) { setConfig(existing); return existing; } const base = await getDefaultConfiguration(); const saved = await saveConfiguration(base.config); setConfig(saved); return saved; } async function start(kind: 'fixture' | 'backtest' | 'research') { try { const saved = await ensureConfig(); const run = await createRun(saved.id, kind); setRuns((items) => [run, ...items]); } catch (error) { setMessage(String(error)); } }
  return <main className="terminal-layout"><Card title="Immutable research catalog" actions={<Badge tone="neutral">READ ONLY</Badge>}><p className="muted">All values are diagnostic evidence. Selected 7.5 is not the paper default; liquidated candidates are retained as exclusions.</p><div className="table-wrap"><table><thead><tr><th>Evidence</th><th>Class</th><th>TOTAL / ROI / DD</th><th>Fees / fills / funding</th><th>Artifact</th></tr></thead><tbody>{catalog.map((item) => <tr key={item.id}><td>{item.title}<br /><span className="muted">{item.limitations.join(' · ')}</span></td><td><Badge tone={item.liquidations ? 'danger' : 'neutral'}>{item.classification}</Badge></td><td>{item.settled_total} / {item.roi} / {item.drawdown_percent}</td><td>{item.fees} / {item.fills} / {item.funding}</td><td>{item.artifact_state}</td></tr>)}</tbody></table></div></Card><Card title="Research runs" actions={<Badge tone="neutral">ISOLATED SUBPROCESS</Badge>}><label className="rules-field"><span>Saved immutable candidate</span><select value={config?.id ?? ''} onChange={(event) => { const next = configs.find((item) => item.id === event.target.value) ?? null; setConfig(next); if (next) window.localStorage.setItem('coinmaster-selected-config', next.id); }}>{configs.map((item) => <option key={item.id} value={item.id}>{item.config_hash.slice(0, 12)} · {item.id.slice(0, 8)}</option>)}</select></label><p className="muted">Native research starts only in an owned local subprocess and blocks honestly when source coverage is missing. Artifact reference never starts a calculation.</p><div className="rules-btn-group rules-btn-group--mb"><Button variant="secondary" onClick={() => void start('fixture')}>Run synthetic P1 fixture</Button><Button variant="primary" onClick={() => void start('backtest')}>Reference selected native research</Button><Button variant="secondary" onClick={() => void start('research')}>Start native research</Button><Button variant="secondary" onClick={load}>Refresh status</Button></div>{message ? <p className="muted">{message}</p> : null}<div className="table-wrap"><table><thead><tr><th>Run</th><th>Status / progress</th><th>Evidence</th><th>Result</th><th /></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td>{run.kind} · {run.id.slice(0, 8)}</td><td><Badge tone={tone(run.status)}>{run.status}{run.progress === null || run.progress === undefined ? '' : ` · ${run.progress}%`}</Badge></td><td>{run.evidence.join(', ')}</td><td>{String(run.report?.terminal_total_usdt ?? run.report?.terminal_total ?? run.report?.catalog_id ?? (run.report as { blockers?: string[] } | undefined)?.blockers?.join(', ') ?? '—')}</td><td>{run.status === 'QUEUED' || run.status === 'RUNNING' || run.status === 'CANCEL_REQUESTED' ? <Button variant="danger" onClick={() => void cancelRun(run.id).then(load)}>Cancel</Button> : null}</td></tr>)}</tbody></table></div></Card></main>;
}

export function RuntimePage() {
  const [state, setState] = useState<HlStagegProjection | null>(null);
  const [message, setMessage] = useState('');
  const load = () => void getHlStagegProjection().then((next) => { setState(next); setMessage(''); }).catch((error: Error) => { setState(null); setMessage(error.message); });
  useEffect(() => { load(); const timer = window.setInterval(load, 5000); return () => window.clearInterval(timer); }, []);
  const runtimeHealthy = state?.projection_state === 'READY' && state.process_state !== 'DATA_STALE/PAUSED' && state.process_state !== 'WORKER_DISCONNECTED';
  const toneForProjection = runtimeHealthy ? 'success' : 'danger';
  const eventRows = (state?.events ?? []).map((event) => ({ ...event, id: `${event.cursor}:${event.event_id}` }));
  const positionRows = (state?.positions ?? []).map((position) => ({ ...position, id: position.instrument_id }));
  const orderRows = (state?.orders ?? []).map((order) => ({ ...order, id: order.client_order_id }));
  const feedRows = Object.entries(state?.feeds ?? {}).map(([instrument_id, feed]) => ({ ...feed, instrument_id, id: instrument_id }));
  const age = (value: number | null | undefined) => value === null || value === undefined ? 'UNKNOWN' : `${(value / 1_000_000_000).toFixed(1)}s`;
  return <main className="terminal-layout">
    <Card title="HL Stage-G Sandbox runtime" actions={<Badge tone={toneForProjection}>{state ? `${state.projection_state} · ${state.process_state}` : 'OFFLINE'}</Badge>}>
      <p className="muted">Isolated instance: <code>hl-stageg-testnet</code> · public MAINNET data · local native Sandbox · read only. This is not <code>coinmaster-paper</code>.</p>
      <div className="stats-grid">
        <Stat label="Native cash" value={state?.account.native_cash ?? 'UNKNOWN'} />
        <Stat label="Equity" value={state?.account.equity ?? 'UNKNOWN'} />
        <Stat label="Free margin" value={state?.account.free_margin ?? 'UNKNOWN'} />
      </div>
      <div className="rules-btn-group rules-btn-group--mb"><Button variant="secondary" onClick={load}>Refresh projection</Button></div>
      <p className="muted">Process: {state?.process_state ?? 'UNKNOWN'} · reconciliation: {state?.reconciliation ?? 'UNKNOWN'} · live order capability: false</p>
      <p className="muted">Candidate: {state?.hashes.candidate_sha256 ?? 'UNKNOWN'} · Strategy: {state?.hashes.strategy_sha256 ?? 'UNKNOWN'} · Policy: {state?.hashes.execution_policy_sha256 ?? 'UNKNOWN'}</p>
      <p className="muted">Warmup: {state?.warmup.state ?? 'UNKNOWN'} ({state?.warmup.rows ?? 'UNKNOWN'} rows) · funding: {state?.funding_state ?? 'UNPOSTED'}</p>
      <p className="muted">Money and PnL remain UNKNOWN unless verified by the native Sandbox projection. Future funding is UNPOSTED; it is not settled cash.</p>
    </Card>
    <Card title="Public feed gates"><DataTable rows={feedRows} emptyText="No public feed observations." mobileTitle={(row) => row.instrument_id} columns={[{ key: 'instrument', header: 'Instrument', render: (row) => row.instrument_id }, { key: 'state', header: 'State', render: (row) => row.state }, { key: 'mark', header: 'Mark', render: (row) => row.mark ?? 'UNKNOWN' }, { key: 'mark-age', header: 'Mark age', render: (row) => age(row.mark_age_ns) }, { key: 'funding', header: 'Funding', render: (row) => row.funding_rate ?? 'UNKNOWN' }, { key: 'funding-age', header: 'Funding age', render: (row) => age(row.funding_age_ns) }]} /></Card>
    <Card title="Sandbox exposure"><DataTable rows={positionRows} emptyText="No projected Sandbox positions." mobileTitle={(row) => row.instrument_id} columns={[{ key: 'instrument', header: 'Instrument', render: (row) => row.instrument_id }, { key: 'quantity', header: 'Quantity', render: (row) => row.signed_quantity }, { key: 'provenance', header: 'Provenance', render: (row) => row.provenance }]} /><DataTable rows={orderRows} emptyText="No projected Sandbox orders." mobileTitle={(row) => row.client_order_id} columns={[{ key: 'order', header: 'Client order', render: (row) => row.client_order_id }, { key: 'instrument', header: 'Instrument', render: (row) => row.instrument_id ?? 'UNKNOWN' }, { key: 'provenance', header: 'Provenance', render: (row) => row.provenance }]} /></Card>
    <Card title="Sandbox event history"><DataTable rows={eventRows} emptyText="No projected Sandbox events." mobileTitle={(row) => `${row.kind} · ${row.event_id}`} columns={[{ key: 'cursor', header: 'Cursor', render: (row) => row.cursor }, { key: 'kind', header: 'Kind', render: (row) => row.kind }, { key: 'event', header: 'Event', render: (row) => row.event_id }, { key: 'provenance', header: 'Provenance', render: (row) => row.provenance }]} /><p className="muted">Event metadata is an audit cursor, not a claimed exchange fill or PnL history.</p></Card>
    <p className="muted">{state?.warnings.join(' · ') || message}</p>
  </main>;
}
