import { useEffect, useState } from 'react';
import { Badge } from '../components/Badge';
import { Button } from '../components/Button';
import { Card } from '../components/Card';
import { cancelRun, createRun, getConfigurations, getDefaultConfiguration, getPreflight, getRuns, getRuntime, saveConfiguration, setApiToken, type Preflight, type Run, type RuntimeState, type StrategyConfig, type StrategyConfiguration } from '../lib/nautilusApi';

type NumberKey = 'ema_period' | 'beta_days' | 'relative_days' | 'z_history_days' | 'wave_history_days' | 'wave_min_count' | 'btc_notional_multiplier' | 'initial_active_fraction' | 'max_gross_to_active' | 'sol_exit_half_z' | 'sol_exit_all_z' | 'sol_max_holding_days' | 'btc_close_trail_fraction' | 'future_sol_margin_fraction' | 'reserve_transfer_fraction' | 'reserve_trigger_multiple';
type NullableNumberKey = 'sol_z_stop' | 'btc_close_stop_fraction' | 'portfolio_loss_limit_fraction';
type ArrayKey = 'wave_quantiles' | 'btc_tp_fractions_initial_qty' | 'sol_size_multipliers_H' | 'sol_entry_z';

function tone(status: string): 'success' | 'danger' | 'neutral' { return status === 'COMPLETED' ? 'success' : status === 'BLOCKED' || status === 'CANCELED' ? 'danger' : 'neutral'; }
function title(key: string) { return key.replaceAll('_', ' '); }

function CsvNumberField({ label, value, onCommit }: { label: string; value: number[]; onCommit: (next: number[]) => void }) {
  const serialized = value.join(',');
  const [draft, setDraft] = useState(serialized);
  useEffect(() => setDraft(serialized), [serialized]);
  function commit() { const next = draft.split(',').map((part) => Number(part.trim())); if (next.length === 3 && next.every(Number.isFinite)) onCommit(next); }
  return <label className="rules-field"><span>{label} (CSV)</span><input value={draft} onChange={(event) => setDraft(event.target.value)} onBlur={commit} /></label>;
}

function NullableNumberField({ label, value, onChange }: { label: string; value: number | null; onChange: (next: number | null) => void }) {
  const enabled = value !== null;
  return <label className="rules-field"><span>{label}</span><input type="checkbox" checked={enabled} onChange={(event) => onChange(event.target.checked ? 0 : null)} /><input type="number" disabled={!enabled} value={value ?? ''} onChange={(event) => { if (event.target.value !== '') onChange(Number(event.target.value)); }} /></label>;
}

export function StrategyPage() {
  const [config, setConfig] = useState<StrategyConfig | null>(null); const [saved, setSaved] = useState<StrategyConfiguration | null>(null); const [preflight, setPreflight] = useState<Preflight | null>(null); const [message, setMessage] = useState(''); const [token, setToken] = useState(''); const [beta, setBeta] = useState(''); const [leverage, setLeverage] = useState('');
  useEffect(() => { void getDefaultConfiguration().then(async (item) => { setConfig(item.config); setPreflight(await getPreflight(item.config, null, null)); }).catch((error: Error) => setMessage(error.message)); }, []);
  function updateNumber(key: NumberKey, value: string) { if (value !== '') setConfig((item) => item ? { ...item, [key]: Number(value) } : item); }
  function updateNullable(key: NullableNumberKey, value: number | null) { setConfig((item) => item ? { ...item, [key]: value } : item); }
  function updateArray(key: ArrayKey, value: number[]) { setConfig((item) => item ? { ...item, [key]: value } : item); }
  async function save() { if (!config) return; try { const next = await saveConfiguration(config); setSaved(next); window.localStorage.setItem('coinmaster-selected-config', next.id); setMessage('Immutable paper configuration saved.'); } catch (error) { setMessage(String(error)); } }
  async function refreshPreflight() { if (!config) return; try { setPreflight(await getPreflight(config, beta || null, leverage || null)); } catch (error) { setMessage(String(error)); } }
  return <main className="terminal-layout">
    <Card title="Local API access" actions={<Badge tone="neutral">LOCAL</Badge>}><label className="rules-field"><span>Operator token</span><input value={token} type="password" onChange={(event) => setToken(event.target.value)} /><Button onClick={() => { setApiToken(token); window.location.reload(); }}>Connect</Button></label></Card>
    <Card title="Strategy candidate" actions={<Badge tone="neutral">PAPER ONLY</Badge>}>
      <p className="muted">Immutable candidate version; all edits retain the exact baseline until saved.</p>
      <div className="rules-form-grid">
        <label className="rules-field"><span>Initial TOTAL</span><input value={config?.initial_total_usdt ?? ''} onChange={(event) => setConfig((item) => item ? { ...item, initial_total_usdt: event.target.value } : item)} /></label>
        <label className="rules-field"><span>Initial active fraction</span><input type="number" value={String(config?.initial_active_fraction ?? '')} onChange={(event) => updateNumber('initial_active_fraction', event.target.value)} /></label>
        <label className="rules-field"><span>Venue</span><select value={config?.venue ?? ''} onChange={(event) => setConfig((item) => item ? { ...item, venue: (event.target.value || null) as StrategyConfig['venue'] } : item)}><option value="">Unselected</option><option value="bybit">Bybit</option><option value="hyperliquid">Hyperliquid</option></select></label>
        {(['ema_period', 'beta_days', 'relative_days', 'z_history_days', 'wave_history_days', 'wave_min_count', 'btc_notional_multiplier', 'max_gross_to_active', 'sol_exit_half_z', 'sol_exit_all_z', 'sol_max_holding_days', 'btc_close_trail_fraction', 'future_sol_margin_fraction', 'reserve_transfer_fraction', 'reserve_trigger_multiple'] as const).map((key) => <label className="rules-field" key={key}><span>{title(key)}</span><input type="number" value={String(config?.[key] ?? '')} onChange={(event) => updateNumber(key, event.target.value)} /></label>)}
        <label className="rules-field"><span>Max parent notional</span><input value={config?.max_parent_notional ?? ''} onChange={(event) => setConfig((item) => item ? { ...item, max_parent_notional: event.target.value } : item)} /></label>
        <label className="rules-field"><span>Include zero waves</span><input type="checkbox" checked={Boolean(config?.include_zero_waves)} onChange={(event) => setConfig((item) => item ? { ...item, include_zero_waves: event.target.checked } : item)} /></label>
        <label className="rules-field"><span>Freeze sigma on first SOL fill</span><input type="checkbox" checked={Boolean(config?.freeze_sigma_on_first_sol_fill)} onChange={(event) => setConfig((item) => item ? { ...item, freeze_sigma_on_first_sol_fill: event.target.checked } : item)} /></label>
        <label className="rules-field"><span>Insufficient margin</span><select value={config?.insufficient_margin ?? 'reject'} onChange={(event) => setConfig((item) => item ? { ...item, insufficient_margin: event.target.value as StrategyConfig['insufficient_margin'] } : item)}><option value="reject">reject</option><option value="clip">clip</option></select></label>
        {config ? <><CsvNumberField label="Wave quantiles" value={config.wave_quantiles} onCommit={(next) => updateArray('wave_quantiles', next)} /><CsvNumberField label="BTC TP fractions / initial qty" value={config.btc_tp_fractions_initial_qty} onCommit={(next) => updateArray('btc_tp_fractions_initial_qty', next)} /><CsvNumberField label="SOL multipliers H" value={config.sol_size_multipliers_H} onCommit={(next) => updateArray('sol_size_multipliers_H', next)} /><CsvNumberField label="SOL entry z" value={config.sol_entry_z} onCommit={(next) => updateArray('sol_entry_z', next)} /><NullableNumberField label="SOL z stop" value={config.sol_z_stop} onChange={(next) => updateNullable('sol_z_stop', next)} /><NullableNumberField label="BTC close stop fraction" value={config.btc_close_stop_fraction} onChange={(next) => updateNullable('btc_close_stop_fraction', next)} /><NullableNumberField label="Portfolio loss limit fraction" value={config.portfolio_loss_limit_fraction} onChange={(next) => updateNullable('portfolio_loss_limit_fraction', next)} /></> : null}
      </div>
      <div className="rules-btn-group rules-btn-group--mb"><Button variant="primary" disabled={!config} onClick={() => void save()}>Save immutable config</Button>{saved ? <Badge tone="success">{saved.config_hash.slice(0, 12)}</Badge> : null}</div>{message ? <p className="muted">{message}</p> : null}
    </Card>
    <Card title="Venue preflight — BTC + three SOL additions" actions={<Badge tone={preflight?.allowed ? 'success' : 'danger'}>{preflight?.allowed ? 'READY' : 'BLOCKED'}</Badge>}><div className="rules-form-grid"><label className="rules-field"><span>Beta (required)</span><input value={beta} onChange={(event) => setBeta(event.target.value)} /></label><label className="rules-field"><span>Selected leverage</span><input value={leverage} onChange={(event) => setLeverage(event.target.value)} /></label></div><Button onClick={() => void refreshPreflight()}>Refresh preview</Button><p className="muted">BTC {preflight?.requested.btc_notional ?? 'UNKNOWN'} · SOL {String((preflight as (Preflight & { sol_additions?: string[] }) | null)?.sol_additions?.join(' / ') ?? 'UNKNOWN')} · cumulative IM/MM {preflight?.im ?? 'UNKNOWN'} / {preflight?.mm ?? 'UNKNOWN'} · {preflight?.reasons.join(' · ')}</p><p className="muted">Parent cap means maximum order size with sufficient collateral, not the starting order.</p></Card>
  </main>;
}

export function ResearchPage() {
  const [config, setConfig] = useState<StrategyConfiguration | null>(null); const [configs, setConfigs] = useState<StrategyConfiguration[]>([]); const [runs, setRuns] = useState<Run[]>([]); const [message, setMessage] = useState(''); async function load() { try { setRuns(await getRuns()); const items = await getConfigurations(); setConfigs(items); const selected = window.localStorage.getItem('coinmaster-selected-config'); setConfig(items.find((item) => item.id === selected) ?? items[0] ?? null); } catch (error) { setMessage(String(error)); } } useEffect(() => { void load(); }, []); async function ensureConfig() { if (config) return config; const selected = window.localStorage.getItem('coinmaster-selected-config'); const existing = (await getConfigurations()).find((item) => item.id === selected); if (existing) { setConfig(existing); return existing; } const base = await getDefaultConfiguration(); const saved = await saveConfiguration(base.config); setConfig(saved); return saved; } async function start(kind: 'fixture' | 'backtest') { try { const saved = await ensureConfig(); const run = await createRun(saved.id, kind); setRuns((items) => [run, ...items]); } catch (error) { setMessage(String(error)); } }
  return <main className="terminal-layout"><Card title="Research runs" actions={<Badge tone="neutral">P3 GATED</Badge>}><label className="rules-field"><span>Saved immutable candidate</span><select value={config?.id ?? ''} onChange={(event) => { const next = configs.find((item) => item.id === event.target.value) ?? null; setConfig(next); if (next) window.localStorage.setItem('coinmaster-selected-config', next.id); }}>{configs.map((item) => <option key={item.id} value={item.id}>{item.config_hash.slice(0, 12)} · {item.id.slice(0, 8)}</option>)}</select></label><p className="muted">Fixture evidence is native P1 smoke only; it is never ranked as real research.</p><div className="rules-btn-group rules-btn-group--mb"><Button variant="secondary" onClick={() => void start('fixture')}>Run synthetic P1 fixture</Button><Button variant="primary" onClick={() => void start('backtest')}>Request native baseline</Button></div>{message ? <p className="muted">{message}</p> : null}<div className="table-wrap"><table><thead><tr><th>Run</th><th>Status</th><th>Evidence</th><th>Terminal TOTAL</th><th /></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td>{run.kind} · {run.id.slice(0, 8)}</td><td><Badge tone={tone(run.status)}>{run.status}</Badge></td><td>{run.evidence.join(', ')}</td><td>{String(run.report?.terminal_total_usdt ?? '—')}</td><td>{run.status === 'QUEUED' ? <Button variant="danger" onClick={() => void cancelRun(run.id).then(load)}>Cancel</Button> : null}</td></tr>)}</tbody></table></div></Card></main>;
}

export function RuntimePage() { const [state, setState] = useState<RuntimeState | null>(null); const [message, setMessage] = useState(''); useEffect(() => { void getRuntime().then(setState).catch((error: Error) => setMessage(error.message)); }, []); return <main className="terminal-layout"><Card title="Runtime" actions={<Badge tone="danger">{state?.status ?? 'OFFLINE'}</Badge>}><div className="stats-grid"><div className="stat"><div className="stat__label">ACTIVE</div><div className="stat__value">{state?.active_usdt ?? '—'}</div></div><div className="stat"><div className="stat__label">RESERVE</div><div className="stat__value">{state?.reserve_usdt ?? '—'}</div></div><div className="stat"><div className="stat__label">TOTAL</div><div className="stat__value">{state?.total_usdt ?? '—'}</div></div></div><p className="muted">{state?.warnings.join(' · ') || message}</p></Card></main>; }
