import { useEffect, useState } from 'react';
import { Badge } from '../components/Badge';
import { Button } from '../components/Button';
import { Card } from '../components/Card';
import { cancelRun, createRun, getDefaultConfiguration, getPreflight, getRuns, getRuntime, saveConfiguration, type Preflight, type Run, type RuntimeState, type StrategyConfiguration } from '../lib/nautilusApi';

function tone(status: string): 'success' | 'danger' | 'neutral' { return status === 'COMPLETED' ? 'success' : status === 'BLOCKED' || status === 'CANCELED' ? 'danger' : 'neutral'; }
export function StrategyPage() {
  const [config, setConfig] = useState<Record<string, unknown> | null>(null); const [saved, setSaved] = useState<StrategyConfiguration | null>(null); const [preflight, setPreflight] = useState<Preflight | null>(null); const [message, setMessage] = useState('');
  useEffect(() => { void Promise.all([getDefaultConfiguration(), getPreflight()]).then(([item, preview]) => { setConfig(item.config); setPreflight(preview); }).catch((error: Error) => setMessage(error.message)); }, []);
  async function save() { if (!config) return; try { setSaved(await saveConfiguration(config)); setMessage('Immutable paper configuration saved.'); } catch (error) { setMessage(String(error)); } }
  return <main className="terminal-layout"><Card title="Strategy candidate" actions={<Badge tone="neutral">PAPER ONLY</Badge>}><p className="muted">btc_sol_wave_overlay_v1 · 1D BTC/SOL. Live controls are unavailable.</p><div className="stats-grid"><div className="stat"><div className="stat__label">Initial TOTAL</div><div className="stat__value">{String(config?.initial_total_usdt ?? '…')} USDT</div></div><div className="stat"><div className="stat__label">Venue</div><div className="stat__value">Unselected</div></div></div><details><summary>Exact baseline, including inactive parameters</summary><pre className="nautilus-pre">{config ? JSON.stringify(config, null, 2) : 'Loading…'}</pre></details><div className="rules-btn-group rules-btn-group--mb"><Button variant="primary" disabled={!config} onClick={() => void save()}>Save immutable config</Button>{saved ? <Badge tone="success">{saved.config_hash.slice(0, 12)}</Badge> : null}</div>{message ? <p className="muted">{message}</p> : null}</Card><Card title="Venue preflight — requested vs allowed" actions={<Badge tone="danger">BLOCKED</Badge>}><div className="stats-grid"><div className="stat"><div className="stat__label">Requested BTC notional</div><div className="stat__value">{preflight?.requested.btc_notional ?? '…'}</div></div><div className="stat"><div className="stat__label">Public-tier IM / MM</div><div className="stat__value">{preflight?.im ?? 'unknown'} / {preflight?.mm ?? 'unknown'}</div></div></div><p className="muted">Allowed: {preflight?.allowed ? 'yes' : 'no'} · {preflight?.reasons.join(' · ')}</p><p className="muted">{preflight?.cap_label}</p></Card></main>;
}
export function ResearchPage() {
  const [config, setConfig] = useState<StrategyConfiguration | null>(null); const [runs, setRuns] = useState<Run[]>([]); const [message, setMessage] = useState(''); async function load() { try { setRuns(await getRuns()); } catch (error) { setMessage(String(error)); } } useEffect(() => { void load(); }, []);
  async function ensureConfig() { if (config) return config; const base = await getDefaultConfiguration(); const saved = await saveConfiguration(base.config); setConfig(saved); return saved; } async function start(kind: 'fixture' | 'backtest') { try { const saved = await ensureConfig(); const run = await createRun(saved.id, kind); setRuns((items) => [run, ...items]); } catch (error) { setMessage(String(error)); } }
  return <main className="terminal-layout"><Card title="Research runs" actions={<Badge tone="neutral">P3 GATED</Badge>}><p className="muted">Fixture evidence is native P1 smoke only; it is never ranked as real research.</p><div className="rules-btn-group rules-btn-group--mb"><Button variant="secondary" onClick={() => void start('fixture')}>Run synthetic P1 fixture</Button><Button variant="primary" onClick={() => void start('backtest')}>Request native baseline</Button></div>{message ? <p className="muted">{message}</p> : null}<div className="table-wrap"><table><thead><tr><th>Run</th><th>Status</th><th>Evidence</th><th>Terminal TOTAL</th><th /></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td>{run.kind} · {run.id.slice(0, 8)}</td><td><Badge tone={tone(run.status)}>{run.status}</Badge></td><td>{run.evidence.join(', ')}</td><td>{String(run.report?.terminal_total_usdt ?? '—')}</td><td>{run.status === 'QUEUED' ? <Button variant="danger" onClick={() => void cancelRun(run.id).then(load)}>Cancel</Button> : null}</td></tr>)}</tbody></table></div></Card></main>;
}
export function RuntimePage() { const [state, setState] = useState<RuntimeState | null>(null); const [message, setMessage] = useState(''); useEffect(() => { void getRuntime().then(setState).catch((error: Error) => setMessage(error.message)); }, []); return <main className="terminal-layout"><Card title="Runtime" actions={<Badge tone="danger">{state?.status ?? 'OFFLINE'}</Badge>}><div className="stats-grid"><div className="stat"><div className="stat__label">ACTIVE</div><div className="stat__value">{state?.active_usdt ?? '—'}</div></div><div className="stat"><div className="stat__label">RESERVE</div><div className="stat__value">{state?.reserve_usdt ?? '—'}</div></div><div className="stat"><div className="stat__label">TOTAL</div><div className="stat__value">{state?.total_usdt ?? '—'}</div></div></div><p className="muted">{state?.warnings.join(' · ') || message}</p></Card></main>; }
