/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime */
        get: operations["runtime_api_v1_runtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/commands/{command}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Command */
        post: operations["command_api_v1_runtime_commands__command__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_runtime_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RuntimeBalances */
        RuntimeBalances: {
            /** Active Usdt */
            active_usdt: string;
            /** Funding State */
            funding_state: string;
            /** Modelled Funding Cash */
            modelled_funding_cash: string;
            /** Native Cash */
            native_cash: string;
            /** Reserve Usdt */
            reserve_usdt: string;
            /** Total Usdt */
            total_usdt: string;
        };
        /** RuntimeCommandResponse */
        RuntimeCommandResponse: {
            /**
             * Command
             * @enum {string}
             */
            command: "pause-new-entries" | "resume-new-entries" | "flatten-paper";
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Mode
             * @constant
             */
            mode: "paper";
            /**
             * Status
             * @enum {string}
             */
            status: "ACCEPTED" | "DUPLICATE";
        };
        /** RuntimeEvent */
        RuntimeEvent: {
            /** Cursor */
            cursor: number;
            /** Event Id */
            event_id: string;
            /** Kind */
            kind: string;
        };
        /** RuntimeEventsResponse */
        RuntimeEventsResponse: {
            /** Events */
            events: components["schemas"]["RuntimeEvent"][];
            /** Next Cursor */
            next_cursor: number;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** RuntimeFeed */
        RuntimeFeed: {
            /** Funding Age Ns */
            funding_age_ns?: number | null;
            /** Funding Rate */
            funding_rate?: string | null;
            /** Mark */
            mark?: string | null;
            /** Mark Age Ns */
            mark_age_ns?: number | null;
            /** Quote Age Ns */
            quote_age_ns?: number | null;
            /** State */
            state: string;
        };
        /** RuntimeFunding */
        RuntimeFunding: {
            /** Cash Delta */
            cash_delta: string;
            /** Event Id */
            event_id: string;
            /** Instrument Id */
            instrument_id: string;
            /** Mark */
            mark: string;
            /** Rate */
            rate: string;
            /** Settlement Ns */
            settlement_ns: number;
            /** State */
            state: string;
        };
        /** RuntimeMargin */
        RuntimeMargin: {
            /** Free Margin */
            free_margin: string;
            /** Im */
            im: string;
            /** Mm */
            mm: string;
        };
        /** RuntimeOrder */
        RuntimeOrder: {
            /** Client Order Id */
            client_order_id: string;
        };
        /** RuntimePosition */
        RuntimePosition: {
            /** Instrument Id */
            instrument_id: string;
            /** Signed Quantity */
            signed_quantity: string;
        };
        /** RuntimeState */
        RuntimeState: {
            balances: components["schemas"]["RuntimeBalances"];
            /** Event Cursor */
            event_cursor: number;
            /** Events */
            events: components["schemas"]["RuntimeEvent"][];
            /** Feeds */
            feeds: {
                [key: string]: components["schemas"]["RuntimeFeed"];
            };
            /** Fees */
            fees: string;
            /** Fills */
            fills: components["schemas"]["RuntimeEvent"][];
            /** Funding */
            funding: components["schemas"]["RuntimeFunding"][];
            /** Lock */
            lock: string;
            margin: components["schemas"]["RuntimeMargin"];
            /**
             * Mode
             * @enum {string}
             */
            mode: "paper" | "UNKNOWN";
            /** Orders */
            orders: components["schemas"]["RuntimeOrder"][];
            /** Positions */
            positions: components["schemas"]["RuntimePosition"][];
            /** Reconciliation */
            reconciliation: string;
            /** Rejects */
            rejects: string;
            strategy: components["schemas"]["RuntimeStrategy"];
            /** Transfers */
            transfers: string;
            /** Version */
            version: string;
            /** Warnings */
            warnings: string[];
            /** Worker State */
            worker_state: string;
        };
        /** RuntimeStrategy */
        RuntimeStrategy: {
            /** Config Hash */
            config_hash: string;
            /** Config Name */
            config_name?: string | null;
            /** Entries Enabled */
            entries_enabled?: boolean | null;
            /** Registered */
            registered?: boolean | null;
            /** Running */
            running?: boolean | null;
            /** Strategy Class */
            strategy_class: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    runtime_api_v1_runtime_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    command_api_v1_runtime_commands__command__post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                authorization?: string | null;
            };
            path: {
                command: "pause-new-entries" | "resume-new-entries" | "flatten-paper";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeCommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_runtime_events_get: {
        parameters: {
            query?: {
                cursor?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
