/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Configs */
        get: operations["list_configs_api_v1_configurations_get"];
        put?: never;
        /** Create Config */
        post: operations["create_config_api_v1_configurations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/configurations/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Default Config */
        get: operations["default_config_api_v1_configurations_default_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/hl-stageg-testnet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hl Stageg Runtime */
        get: operations["hl_stageg_runtime_api_v1_instances_hl_stageg_testnet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/hl-stageg-testnet/controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hl Stageg Control Capabilities */
        get: operations["hl_stageg_control_capabilities_api_v1_instances_hl_stageg_testnet_controls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/hl-stageg-testnet/controls/reset-deposit-protection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Hl Stageg Deposit Protection */
        post: operations["reset_hl_stageg_deposit_protection_api_v1_instances_hl_stageg_testnet_controls_reset_deposit_protection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/hl-stageg-testnet/controls/set-deposit-protection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Hl Stageg Deposit Protection */
        post: operations["set_hl_stageg_deposit_protection_api_v1_instances_hl_stageg_testnet_controls_set_deposit_protection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/hl-stageg-testnet/controls/{command}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hl Stageg Control Command */
        post: operations["hl_stageg_control_command_api_v1_instances_hl_stageg_testnet_controls__command__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/hl-stageg-testnet/strategy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hl Stageg Strategy */
        get: operations["hl_stageg_strategy_api_v1_instances_hl_stageg_testnet_strategy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preflight */
        post: operations["preflight_api_v1_preflight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research Capability */
        get: operations["research_capability_api_v1_research_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research Catalog */
        get: operations["research_catalog_api_v1_research_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/catalog/{catalog_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research Catalog Detail */
        get: operations["research_catalog_detail_api_v1_research_catalog__catalog_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Report */
        get: operations["run_report_api_v1_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime */
        get: operations["runtime_api_v1_runtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/commands/{command}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Command */
        post: operations["command_api_v1_runtime_commands__command__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_runtime_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/venue-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Venue Profiles */
        get: operations["venue_profiles_api_v1_venue_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfigurationInput */
        ConfigurationInput: {
            config: components["schemas"]["StrategyConfig"];
        };
        /** ConfigurationRecord */
        ConfigurationRecord: {
            config: components["schemas"]["StrategyConfig"];
            /** Config Hash */
            config_hash: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HlStagegAccount */
        HlStagegAccount: {
            /** Equity */
            equity?: string | null;
            /** Fees */
            fees?: string | null;
            /** Free Margin */
            free_margin?: string | null;
            /** Im */
            im?: string | null;
            /** Mark State */
            mark_state?: ("CURRENT" | "STALE_OR_MISSING") | null;
            /** Mm */
            mm?: string | null;
            /** Native Cash */
            native_cash?: string | null;
            /** Native Free */
            native_free?: string | null;
            /** Native Locked */
            native_locked?: string | null;
            /** Observed At Ns */
            observed_at_ns?: number | null;
            /** Realized Pnl Net Fees */
            realized_pnl_net_fees?: string | null;
            /**
             * Status
             * @default UNAVAILABLE
             * @enum {string}
             */
            status: "AVAILABLE" | "PARTIAL" | "UNAVAILABLE";
            /** Unrealized Pnl */
            unrealized_pnl?: string | null;
        };
        /** HlStagegControlAction */
        HlStagegControlAction: {
            /** Blocker */
            blocker?: string | null;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Requires Confirmation
             * @default false
             */
            requires_confirmation: boolean;
        };
        /** HlStagegControlCommand */
        HlStagegControlCommand: {
            /**
             * Command
             * @enum {string}
             */
            command: "pause-new-entries" | "resume-new-entries";
            /**
             * Entry Control
             * @enum {string}
             */
            entry_control: "RUNNING" | "PAUSED";
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Instance Id
             * @constant
             */
            instance_id: "hl-stageg-testnet";
            /**
             * Status
             * @enum {string}
             */
            status: "ACCEPTED" | "DUPLICATE";
        };
        /** HlStagegControls */
        HlStagegControls: {
            flatten: components["schemas"]["HlStagegControlAction"];
            /**
             * Instance Id
             * @default hl-stageg-testnet
             * @constant
             */
            instance_id: "hl-stageg-testnet";
            /**
             * Mode
             * @default sandbox
             * @constant
             */
            mode: "sandbox";
            pause: components["schemas"]["HlStagegControlAction"];
            /**
             * Projection State
             * @enum {string}
             */
            projection_state: "READY" | "STALE" | "UNAVAILABLE" | "INVALID";
            promotion: components["schemas"]["HlStagegControlAction"];
            resume: components["schemas"]["HlStagegControlAction"];
        };
        /** HlStagegDepositProtection */
        HlStagegDepositProtection: {
            /** Currency */
            currency?: string | null;
            /** Drawdown Limit Percent */
            drawdown_limit_percent: number;
            /** Equity */
            equity?: string | null;
            /** High Water Equity */
            high_water_equity?: string | null;
            /** Last Daily Close Utc */
            last_daily_close_utc?: string | null;
            /** Observed At Ns */
            observed_at_ns?: number | null;
            /**
             * State
             * @enum {string}
             */
            state: "NOT_INITIALIZED" | "RECOVERY_REQUIRED" | "ARMED" | "EQUITY_UNAVAILABLE" | "EXITING" | "TRIPPED_FLAT" | "EXIT_INCOMPLETE";
            /** Threshold Equity */
            threshold_equity?: string | null;
            /** Trigger */
            trigger?: string | null;
        };
        /** HlStagegEntryControl */
        HlStagegEntryControl: {
            /**
             * Capability
             * @enum {string}
             */
            capability: "READY" | "UNAVAILABLE";
            /**
             * State
             * @enum {string}
             */
            state: "RUNNING" | "PAUSED";
        };
        /** HlStagegEvent */
        HlStagegEvent: {
            /** Cursor */
            cursor: number;
            /** Event Id */
            event_id: string;
            /** Kind */
            kind: string;
            /**
             * Provenance
             * @default SANDBOX
             * @constant
             */
            provenance: "SANDBOX";
        };
        /** HlStagegHashes */
        HlStagegHashes: {
            /** Candidate Sha256 */
            candidate_sha256: string;
            /** Execution Policy Sha256 */
            execution_policy_sha256: string;
            /** Strategy Sha256 */
            strategy_sha256: string;
        };
        /** HlStagegOrder */
        HlStagegOrder: {
            /** Account Id */
            account_id?: string | null;
            /** Client Order Id */
            client_order_id: string;
            /** Filled Quantity */
            filled_quantity?: string | null;
            /** Instrument Id */
            instrument_id?: string | null;
            /** Leaves Quantity */
            leaves_quantity?: string | null;
            /** Order Type */
            order_type?: string | null;
            /** Post Only */
            post_only?: boolean | null;
            /** Price */
            price?: string | null;
            /**
             * Provenance
             * @default SANDBOX
             * @constant
             */
            provenance: "SANDBOX";
            /** Quantity */
            quantity?: string | null;
            /** Reduce Only */
            reduce_only?: boolean | null;
            /** Side */
            side?: string | null;
            /** Status */
            status?: string | null;
            /** Submitted At Ns */
            submitted_at_ns?: number | null;
            /** Time In Force */
            time_in_force?: string | null;
            /** Updated At Ns */
            updated_at_ns?: number | null;
            /** Venue Order Id */
            venue_order_id?: string | null;
        };
        /** HlStagegPosition */
        HlStagegPosition: {
            /** Instrument Id */
            instrument_id: string;
            /**
             * Provenance
             * @default SANDBOX
             * @constant
             */
            provenance: "SANDBOX";
            /** Signed Quantity */
            signed_quantity: string;
        };
        /** HlStagegProjection */
        HlStagegProjection: {
            account: components["schemas"]["HlStagegAccount"];
            deposit_protection?: components["schemas"]["HlStagegDepositProtection"] | null;
            entry_control: components["schemas"]["HlStagegEntryControl"];
            /**
             * Environment
             * @constant
             */
            environment: "mainnet-public";
            /** Event Cursor */
            event_cursor: number;
            /** Events */
            events: components["schemas"]["HlStagegEvent"][];
            /** Feeds */
            feeds: {
                [key: string]: components["schemas"]["RuntimeFeed"];
            };
            /** Funding State */
            funding_state: string;
            /** Gates */
            gates: {
                [key: string]: string | boolean;
            };
            hashes: components["schemas"]["HlStagegHashes"];
            /**
             * Instance Id
             * @constant
             */
            instance_id: "hl-stageg-testnet";
            /**
             * Live Order Capability
             * @default false
             * @constant
             */
            live_order_capability: false;
            /**
             * Mode
             * @constant
             */
            mode: "sandbox";
            /** Native Thread Alive */
            native_thread_alive?: boolean | null;
            /** Observed At Ns */
            observed_at_ns?: number | null;
            /** Orders */
            orders: components["schemas"]["HlStagegOrder"][];
            /** Positions */
            positions: components["schemas"]["HlStagegPosition"][];
            /** Process State */
            process_state: string;
            /**
             * Projection State
             * @enum {string}
             */
            projection_state: "READY" | "STALE" | "UNAVAILABLE" | "INVALID";
            /**
             * Provenance
             * @constant
             */
            provenance: "SANDBOX_LOCAL_READ_ONLY_WORKER_PROJECTION";
            /** Reconciliation */
            reconciliation: string;
            /** Recovery Capability */
            recovery_capability?: string | null;
            /** Recovery Required */
            recovery_required?: boolean | null;
            /** Run Epoch */
            run_epoch?: string | null;
            /** Sandbox Starting Cash Usdc */
            sandbox_starting_cash_usdc?: string | null;
            /**
             * Version
             * @constant
             */
            version: "hl-stageg-projection-v1";
            /** Virtual Capital Resets On Flat Restart */
            virtual_capital_resets_on_flat_restart?: boolean | null;
            warmup: components["schemas"]["HlStagegWarmup"];
            /** Warnings */
            warnings: string[];
        };
        /** HlStagegProtectionCommand */
        HlStagegProtectionCommand: {
            /**
             * Command
             * @enum {string}
             */
            command: "set-deposit-protection" | "reset-deposit-protection";
            deposit_protection: components["schemas"]["HlStagegDepositProtection"];
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Instance Id
             * @constant
             */
            instance_id: "hl-stageg-testnet";
            /**
             * Status
             * @constant
             */
            status: "APPLIED";
        };
        /** HlStagegProtectionCommandRequest */
        HlStagegProtectionCommandRequest: {
            /** Drawdown Limit Percent */
            drawdown_limit_percent: number;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** HlStagegProtectionResetRequest */
        HlStagegProtectionResetRequest: {
            /**
             * Confirm
             * @constant
             */
            confirm: true;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** HlStagegStrategy */
        HlStagegStrategy: {
            /** Account Fee Schedule */
            account_fee_schedule: string;
            /** Account Margin */
            account_margin: string;
            /** Candidate */
            candidate: {
                [key: string]: string;
            };
            /** Capital Assumption */
            capital_assumption: string;
            /**
             * Environment
             * @constant
             */
            environment: "mainnet-public";
            /** Funding Treatment */
            funding_treatment: string;
            hashes: components["schemas"]["HlStagegHashes"];
            /**
             * Instance Id
             * @constant
             */
            instance_id: "hl-stageg-testnet";
            /**
             * Mode
             * @constant
             */
            mode: "sandbox";
            /**
             * Promotion Enabled
             * @default false
             * @constant
             */
            promotion_enabled: false;
            /**
             * Promotion Reason
             * @constant
             */
            promotion_reason: "SEPARATE_NATIVE_LIFECYCLE_GATE_REQUIRED";
            /** Public Venue Profile */
            public_venue_profile: string;
            /** Research Comparison Assumption */
            research_comparison_assumption: string;
            /**
             * Running State
             * @enum {string}
             */
            running_state: "RUNNING_MATCH" | "MISMATCH" | "NOT_CONFIRMED";
            /**
             * Source State
             * @enum {string}
             */
            source_state: "SEALED_SOURCE_CHECKED" | "INVALID";
            /** Strategy Id */
            strategy_id: string;
            /**
             * Version
             * @constant
             */
            version: "hl-stageg-strategy-v1";
            /** Warnings */
            warnings: string[];
        };
        /** HlStagegWarmup */
        HlStagegWarmup: {
            /** Rows */
            rows?: number | null;
            /** State */
            state: string;
        };
        /** PreflightInput */
        PreflightInput: {
            /**
             * Active Usdt
             * @default 10000
             */
            active_usdt: string;
            /** Beta */
            beta?: string | null;
            /** Btc Notional */
            btc_notional: string;
            /** Selected Leverage */
            selected_leverage?: string | null;
            /** Sol Multipliers */
            sol_multipliers: number[];
            /**
             * Venue
             * @enum {string}
             */
            venue: "bybit" | "hyperliquid";
        };
        /** ResearchCapabilities */
        ResearchCapabilities: {
            /** Baseline Blockers */
            baseline_blockers: string[];
            /** Baseline End Exclusive */
            baseline_end_exclusive: string;
            /**
             * Baseline Objective
             * @constant
             */
            baseline_objective: "TOTAL only";
            /** Baseline Start */
            baseline_start: string;
            /**
             * Baseline State
             * @enum {string}
             */
            baseline_state: "READY" | "BLOCKED";
            /** Optimizer Blocker */
            optimizer_blocker: string | null;
            /** Optimizer Blockers */
            optimizer_blockers: string[];
            /** Optimizer Search */
            optimizer_search: {
                [key: string]: unknown;
            };
            /** Optimizer Source Manifest Sha256 */
            optimizer_source_manifest_sha256: string | null;
            /**
             * Optimizer State
             * @enum {string}
             */
            optimizer_state: "READY" | "BLOCKED";
        };
        /** ResearchCatalogDetail */
        ResearchCatalogDetail: {
            /** Artifact */
            artifact: string;
            /** Artifact State */
            artifact_state: string;
            /** Classification */
            classification: string;
            /** Drawdown Percent */
            drawdown_percent: string;
            /** Fees */
            fees: string;
            /** Fills */
            fills: number;
            /** Funding */
            funding: number;
            /** Id */
            id: string;
            /** Interval */
            interval: string;
            /** Interval Cash */
            interval_cash: string;
            /** Kind */
            kind: string;
            /** Limitations */
            limitations: string[];
            /** Liquidations */
            liquidations: number;
            /** Roi */
            roi: string;
            /** Selected */
            selected: boolean;
            /** Settled Total */
            settled_total: string;
            /** Sha256 */
            sha256: string;
            /** Supersession */
            supersession: string;
            /** Title */
            title: string;
            /** Verified Detail */
            verified_detail?: {
                [key: string]: unknown;
            } | null;
            /** Warmup */
            warmup: string;
        };
        /** ResearchCatalogEntry */
        ResearchCatalogEntry: {
            /** Artifact */
            artifact: string;
            /** Artifact State */
            artifact_state: string;
            /** Classification */
            classification: string;
            /** Drawdown Percent */
            drawdown_percent: string;
            /** Fees */
            fees: string;
            /** Fills */
            fills: number;
            /** Funding */
            funding: number;
            /** Id */
            id: string;
            /** Interval */
            interval: string;
            /** Interval Cash */
            interval_cash: string;
            /** Kind */
            kind: string;
            /** Limitations */
            limitations: string[];
            /** Liquidations */
            liquidations: number;
            /** Roi */
            roi: string;
            /** Selected */
            selected: boolean;
            /** Settled Total */
            settled_total: string;
            /** Sha256 */
            sha256: string;
            /** Supersession */
            supersession: string;
            /** Title */
            title: string;
            /** Warmup */
            warmup: string;
        };
        /** RunInput */
        RunInput: {
            /** Config Id */
            config_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "fixture" | "backtest" | "paper" | "research";
            /** Optimizer Search */
            optimizer_search?: {
                [key: string]: unknown;
            } | null;
            /** Research Command */
            research_command?: string | null;
        };
        /** RunRecord */
        RunRecord: {
            /** Cancel Requested At */
            cancel_requested_at?: string | null;
            /** Command Name */
            command_name?: string | null;
            /** Config Id */
            config_id: string;
            /** Created At */
            created_at: string;
            /** Evidence */
            evidence: string[];
            /** Finished At */
            finished_at?: string | null;
            /** Heartbeat At */
            heartbeat_at?: string | null;
            /** Id */
            id: string;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Kind */
            kind: string;
            /** Pid */
            pid?: number | null;
            /** Process Group */
            process_group?: number | null;
            /** Process Identity */
            process_identity?: string | null;
            /** Progress */
            progress?: number | null;
            /** Report */
            report?: {
                [key: string]: unknown;
            } | null;
            /** Request Hash */
            request_hash?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Work Dir */
            work_dir?: string | null;
        };
        /** RuntimeBalances */
        RuntimeBalances: {
            /** Active Usdt */
            active_usdt: string;
            /** Funding State */
            funding_state: string;
            /** Modelled Funding Cash */
            modelled_funding_cash: string;
            /** Native Cash */
            native_cash: string;
            /** Reserve Usdt */
            reserve_usdt: string;
            /** Total Usdt */
            total_usdt: string;
        };
        /** RuntimeCommandResponse */
        RuntimeCommandResponse: {
            /**
             * Command
             * @enum {string}
             */
            command: "pause-new-entries" | "resume-new-entries" | "flatten-paper";
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Mode
             * @constant
             */
            mode: "paper";
            /**
             * Status
             * @enum {string}
             */
            status: "ACCEPTED" | "DUPLICATE";
        };
        /** RuntimeEvent */
        RuntimeEvent: {
            /** Cursor */
            cursor: number;
            /** Event Id */
            event_id: string;
            /** Kind */
            kind: string;
        };
        /** RuntimeEventsResponse */
        RuntimeEventsResponse: {
            /** Events */
            events: components["schemas"]["RuntimeEvent"][];
            /** Next Cursor */
            next_cursor: number;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** RuntimeFeed */
        RuntimeFeed: {
            /** Funding Age Ns */
            funding_age_ns?: number | null;
            /** Funding Rate */
            funding_rate?: string | null;
            /** Mark */
            mark?: string | null;
            /** Mark Age Ns */
            mark_age_ns?: number | null;
            /** Next Funding Ns */
            next_funding_ns?: number | null;
            /** Quote Age Ns */
            quote_age_ns?: number | null;
            /** State */
            state: string;
        };
        /** RuntimeFunding */
        RuntimeFunding: {
            /** Cash Delta */
            cash_delta: string;
            /** Event Id */
            event_id: string;
            /** Instrument Id */
            instrument_id: string;
            /** Mark */
            mark: string;
            /** Rate */
            rate: string;
            /** Settlement Ns */
            settlement_ns: number;
            /** State */
            state: string;
        };
        /** RuntimeMargin */
        RuntimeMargin: {
            /** Free Margin */
            free_margin: string;
            /** Im */
            im: string;
            /** Mm */
            mm: string;
        };
        /** RuntimeOrder */
        RuntimeOrder: {
            /** Client Order Id */
            client_order_id: string;
        };
        /** RuntimePosition */
        RuntimePosition: {
            /** Instrument Id */
            instrument_id: string;
            /** Signed Quantity */
            signed_quantity: string;
        };
        /** RuntimeState */
        RuntimeState: {
            balances: components["schemas"]["RuntimeBalances"];
            /** Event Cursor */
            event_cursor: number;
            /** Events */
            events: components["schemas"]["RuntimeEvent"][];
            /** Feeds */
            feeds: {
                [key: string]: components["schemas"]["RuntimeFeed"];
            };
            /** Fees */
            fees: string;
            /** Fills */
            fills: components["schemas"]["RuntimeEvent"][];
            /** Funding */
            funding: components["schemas"]["RuntimeFunding"][];
            /** Live Order Capability */
            live_order_capability?: boolean | null;
            /** Lock */
            lock: string;
            margin: components["schemas"]["RuntimeMargin"];
            /**
             * Mode
             * @enum {string}
             */
            mode: "paper" | "UNKNOWN";
            /** Orders */
            orders: components["schemas"]["RuntimeOrder"][];
            /** Positions */
            positions: components["schemas"]["RuntimePosition"][];
            /** Reconciliation */
            reconciliation: string;
            /** Rejects */
            rejects: string;
            strategy: components["schemas"]["RuntimeStrategy"];
            /** Transfers */
            transfers: string;
            /** Version */
            version: string;
            /** Warnings */
            warnings: string[];
            /** Worker State */
            worker_state: string;
        };
        /** RuntimeStrategy */
        RuntimeStrategy: {
            /** Config Hash */
            config_hash: string;
            /** Config Name */
            config_name?: string | null;
            /** Entries Enabled */
            entries_enabled?: boolean | null;
            /** Registered */
            registered?: boolean | null;
            /** Running */
            running?: boolean | null;
            /** Strategy Class */
            strategy_class: string;
        };
        /** StrategyConfig */
        StrategyConfig: {
            /** Beta Days */
            beta_days: number;
            /** Btc Close Stop Fraction */
            btc_close_stop_fraction: number | null;
            /** Btc Close Trail Fraction */
            btc_close_trail_fraction: number;
            /** Btc Notional Multiplier */
            btc_notional_multiplier: number;
            /** Btc Tp Fractions Initial Qty */
            btc_tp_fractions_initial_qty: number[];
            /** Ema Period */
            ema_period: number;
            /** Freeze Sigma On First Sol Fill */
            freeze_sigma_on_first_sol_fill: boolean;
            /** Future Sol Margin Fraction */
            future_sol_margin_fraction: number;
            /** Include Zero Waves */
            include_zero_waves: boolean;
            /** Initial Active Fraction */
            initial_active_fraction: number;
            /** Initial Total Usdt */
            initial_total_usdt: string;
            /**
             * Insufficient Margin
             * @enum {string}
             */
            insufficient_margin: "reject" | "clip";
            /**
             * Live Enabled
             * @constant
             */
            live_enabled: false;
            /** Max Gross To Active */
            max_gross_to_active: number;
            /** Max Parent Notional */
            max_parent_notional: string;
            /**
             * Mode
             * @constant
             */
            mode: "paper";
            /** Portfolio Loss Limit Fraction */
            portfolio_loss_limit_fraction: number | null;
            /**
             * Post Liquidation
             * @constant
             */
            post_liquidation: "restart_from_reserve_else_pause";
            /**
             * Regime
             * @constant
             */
            regime: "close_vs_ema";
            /** Relative Days */
            relative_days: number;
            /** Reserve Transfer Fraction */
            reserve_transfer_fraction: number;
            /** Reserve Trigger Multiple */
            reserve_trigger_multiple: number;
            /**
             * Restart Target
             * @constant
             */
            restart_target: "initial_active_seed";
            /**
             * Signal Timeframe
             * @constant
             */
            signal_timeframe: "1D";
            /**
             * Sol Direction
             * @constant
             */
            sol_direction: "opposite_btc";
            /**
             * Sol Entry Eligibility
             * @constant
             */
            sol_entry_eligibility: "persistent_after_btc_level";
            /** Sol Entry Z */
            sol_entry_z: number[];
            /** Sol Exit All Z */
            sol_exit_all_z: number;
            /** Sol Exit Half Z */
            sol_exit_half_z: number;
            /** Sol Max Holding Days */
            sol_max_holding_days: number;
            /** Sol Size Multipliers H */
            sol_size_multipliers_H: number[];
            /** Sol Z Stop */
            sol_z_stop: number | null;
            /**
             * Strategy Id
             * @constant
             */
            strategy_id: "btc_sol_wave_overlay_v1";
            /** Venue */
            venue: ("bybit" | "hyperliquid") | null;
            /** Wave History Days */
            wave_history_days: number;
            /** Wave Min Count */
            wave_min_count: number;
            /** Wave Quantiles */
            wave_quantiles: number[];
            /** Z History Days */
            z_history_days: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_configs_api_v1_configurations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_config_api_v1_configurations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigurationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    default_config_api_v1_configurations_default_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationInput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hl_stageg_runtime_api_v1_instances_hl_stageg_testnet_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HlStagegProjection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hl_stageg_control_capabilities_api_v1_instances_hl_stageg_testnet_controls_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HlStagegControls"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_hl_stageg_deposit_protection_api_v1_instances_hl_stageg_testnet_controls_reset_deposit_protection_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HlStagegProtectionResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HlStagegProtectionCommand"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_hl_stageg_deposit_protection_api_v1_instances_hl_stageg_testnet_controls_set_deposit_protection_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HlStagegProtectionCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HlStagegProtectionCommand"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hl_stageg_control_command_api_v1_instances_hl_stageg_testnet_controls__command__post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                command: "pause-new-entries" | "resume-new-entries";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HlStagegControlCommand"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hl_stageg_strategy_api_v1_instances_hl_stageg_testnet_strategy_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HlStagegStrategy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preflight_api_v1_preflight_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreflightInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_capability_api_v1_research_capabilities_get: {
        parameters: {
            query?: {
                config_id?: string | null;
            };
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchCapabilities"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_catalog_api_v1_research_catalog_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchCatalogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_catalog_detail_api_v1_research_catalog__catalog_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                catalog_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchCatalogDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_report_api_v1_runs__run_id__report_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runtime_api_v1_runtime_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    command_api_v1_runtime_commands__command__post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path: {
                command: "pause-new-entries" | "resume-new-entries" | "flatten-paper";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeCommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_runtime_events_get: {
        parameters: {
            query?: {
                cursor?: number;
            };
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    venue_profiles_api_v1_venue_profiles_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
